---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3364659941-5NqrCCLNUsT0P3bEDSKUINDy0D29AAioZF72bYO
:access_token_secret: faLyVSWgnyUTzaqzEhvV66fyHrxW7ai0agguqLzUfG44U
